Stopped on time - objective value 19686.00000000
      0 x[r,Client]                                                             8                     -87
      1 x[r,CertificateTemplate]                                                1                    -173
      2 x[r,Course]                                                             1                      -1
      3 x[r,Role]                                                              34                      87
      4 x[r,User]                                                              27                     173
      5 x[r,CourseSession]                                                      7                    -259
      6 x[r,Clinic]                                                            35                      87
      7 x[r,Location]                                                          16         -1.00000000000001
      8 x[r,Therapist]                                                         25                       1
      9 x[r,Instructor]                                                        17                     171
     10 x[c,Client]                                                            28                     259
     11 x[c,CertificateTemplate]                                               28                      87
     12 x[c,Course]                                                            16                      -1
     13 x[c,Role]                                                              27                    -173
     14 x[c,User]                                                              27                     -85
     15 x[c,CourseSession]                                                     14                    -345
     16 x[c,Clinic]                                                            16                       0
     17 x[c,Location]                                                          16                       0
     18 x[c,Therapist]                                                         16                      85
     19 x[c,Instructor]                                                        27                     173
     20 center_dist[r,Client]                                                 9.5                       0
     21 center_dist[r,CertificateTemplate]                                   17.5                       0
     22 center_dist[r,Course]                                                  18                       0
     23 center_dist[r,Role]                                                    15                       0
     24 center_dist[r,User]                                                   8.5                       0
     25 center_dist[r,CourseSession]                                         10.5                       0
     26 center_dist[r,Clinic]                                                  17                       0
     27 center_dist[r,Location]                                               1.5                       0
     28 center_dist[r,Therapist]                                                8                       0
     30 center_dist[c,Client]                                                11.5                       0
     31 center_dist[c,CertificateTemplate]                                     12                       0
     32 center_dist[c,Course]                                                   1                       0
     33 center_dist[c,Role]                                                    10                       0
     34 center_dist[c,User]                                                  10.5                       0
     35 center_dist[c,CourseSession]                                            1                       0
     36 center_dist[c,Clinic]                                     0.500000000000006                       0
     37 center_dist[c,Location]                                   0.500000000000006                       0
     38 center_dist[c,Therapist]                                              0.5                       0
     39 center_dist[c,Instructor]                                              11                       0
     40 dist[r,Client,CertificateTemplate]                                      8                       0
     41 dist[r,Client,CourseSession]                                            1                       0
     42 dist[r,Client,Instructor]                                             9.5                       0
     43 dist[r,Client,Location]                                                 8                       0
     44 dist[r,Client,User]                                                    18                       0
     45 dist[r,CertificateTemplate,CourseSession]                               7                       0
     46 dist[r,Course,CourseSession]                                          7.5                       0
     47 dist[r,CourseSession,Instructor]                                     10.5                       0
     48 dist[r,Instructor,Location]                                           1.5                       0
     49 dist[r,Clinic,Location]                                              18.5                       0
     50 dist[r,Clinic,Therapist]                                  8.99999999999999                       0
     51 dist[r,Location,Therapist]                                            9.5                       0
     52 dist[r,Location,CourseSession]                                          9                       0
     53 dist[r,Therapist,CourseSession]                                      18.5                       0
     54 dist[r,Role,User]                                                     6.5                       0
     55 dist[r,User,Instructor]                                               8.5                       0
     56 dist[r,User,Therapist]                                    0.499999999999996                       0
     57 dist[c,Client,CertificateTemplate]                                    0.5                       0
     58 dist[c,Client,CourseSession]                                         12.5                       0
     59 dist[c,Client,Instructor]                                 0.499999999999998                       0
     60 dist[c,Client,Location]                                                12                       0
     61 dist[c,Client,User]                                                     1                       0
     62 dist[c,CertificateTemplate,CourseSession]                              13                       0
     64 dist[c,CourseSession,Instructor]                                       12                       0
     65 dist[c,Instructor,Location]                                          11.5                       0
     69 dist[c,Location,CourseSession]                            0.499999999999997                       0
     70 dist[c,Therapist,CourseSession]                           0.500000000000001                       0
     71 dist[c,Role,User]                                                     0.5                       0
     72 dist[c,User,Instructor]                                               0.5                       0
     73 dist[c,User,Therapist]                                                 11                       0
     74 zV[r,rt,Client,CertificateTemplate]                                     1                       0
     78 zV[r,rt,Client,Course]                                                  1                       0
     84 zV[r,lb,Client,Role]                                                    1                       0
     88 zV[r,lb,Client,User]                                                    1                       0
     91 zV[c,rt,Client,CourseSession]                                           1                       0
     95 zV[c,rt,Client,Clinic]                                                  1                       0
     99 zV[c,rt,Client,Location]                                                1                       0
    103 zV[c,rt,Client,Therapist]                                               1                       0
    108 zV[r,lb,Client,Instructor]                                              1                       0
    111 zV[c,rt,CertificateTemplate,Course]                                     1                       0
    116 zV[r,lb,CertificateTemplate,Role]                                       1                       0
    120 zV[r,lb,CertificateTemplate,User]                                       1                       0
    123 zV[c,rt,CertificateTemplate,CourseSession]                              1                       0
    128 zV[r,lb,CertificateTemplate,Clinic]                                     1                       0
    131 zV[c,rt,CertificateTemplate,Location]                                   1                       0
    136 zV[r,lb,CertificateTemplate,Therapist]                                  1                       0
    140 zV[r,lb,CertificateTemplate,Instructor]                                 1                       0
    145 zV[c,lb,Course,Role]                                                    1                       0
    148 zV[r,lb,Course,User]                                                    1                       0
    152 zV[r,lb,Course,CourseSession]                                           1                       0
    156 zV[r,lb,Course,Clinic]                                                  1                       0
    160 zV[r,lb,Course,Location]                                                1                       0
    164 zV[r,lb,Course,Therapist]                                               1                       0
    168 zV[r,lb,Course,Instructor]                                              1                       0
    170 zV[r,rt,Role,User]                                                      1                       0
    174 zV[r,rt,Role,CourseSession]                                             1                       0
    179 zV[c,rt,Role,Clinic]                                                    1                      53
    183 zV[c,rt,Role,Location]                                                  1                    4611
    187 zV[c,rt,Role,Therapist]                                                 1                       0
    190 zV[r,rt,Role,Instructor]                                                1                       0
    194 zV[r,rt,User,CourseSession]                                             1                       0
    200 zV[r,lb,User,Clinic]                                                    1                       0
    202 zV[r,rt,User,Location]                                                  1                       0
    207 zV[c,rt,User,Therapist]                                                 1                       0
    210 zV[r,rt,User,Instructor]                                                1                       0
    216 zV[r,lb,CourseSession,Clinic]                                           1                       0
    220 zV[r,lb,CourseSession,Location]                                         1                       0
    224 zV[r,lb,CourseSession,Therapist]                                        1                       0
    228 zV[r,lb,CourseSession,Instructor]                                       1                       0
    230 zV[r,rt,Clinic,Location]                                                1                       0
    234 zV[r,rt,Clinic,Therapist]                                               1                       0
    238 zV[r,rt,Clinic,Instructor]                                              1                       0
    244 zV[r,lb,Location,Therapist]                                             1                       0
    249 zV[c,lb,Location,Instructor]                                            1                       0
    253 zV[c,lb,Therapist,Instructor]                                           1                       0
